# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-12 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('assess_file', models.FileField(blank=True, null=True, upload_to=main.models.assessment_directory_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.assessment_image_directory_path)),
                ('code_editor_filler', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_submission', models.TextField(blank=True, null=True)),
                ('errors_list', models.TextField(default=b'')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempted', models.BooleanField(default=False)),
                ('number_of_attempts', models.PositiveSmallIntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_record', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('html_notebook', models.FileField(null=True, upload_to=main.models.notebook_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks_on_content_tab_counter', models.PositiveSmallIntegerField(default=0)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('date_enrolled', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('notebook', models.FileField(blank=True, null=True, upload_to=main.models.notebook_directory_path)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateds', to='main.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_progress', models.ManyToManyField(through='main.AssessmentProgress', to='main.Assessment')),
                ('content_progress', models.ManyToManyField(through='main.ContentProgress', to='main.Content')),
                ('course_progress', models.ManyToManyField(through='main.CourseProgress', to='main.Course')),
                ('module_progress', models.ManyToManyField(through='main.ModuleProgress', to='main.Module')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('video_URL', models.URLField(null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.Module')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_notes', models.TextField(null=True)),
                ('video_timepoint', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('clicks_on_video_open_counter', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Video')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='video_progress',
            field=models.ManyToManyField(through='main.VideoProgress', to='main.Video'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='main.Module'),
        ),
        migrations.AddField(
            model_name='assessmentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='main.Module'),
        ),
    ]
